name: Guilds
main: guilds.GuildsBasic
version: 1.0.0
author: largo7
website: http://eredrim.fr
softdepend: [WorldGuard]
commands:
  guilds:
    description: Various commands for Guilds.
    usage: /<command> <arg>
  base:
    description: TP to Base.
    usage: /<command>
  gchat:
    description: Guild chat
    aliases: [g]
    usage: /<command> <arg>
permissions:
    guilds.*:
        description: Gives access to all guilds commands
        children:
            guilds.admin.kick: true
            guilds.admin.toggle: true
            guilds.admin.settings: true
            guilds.admin.setting: true
            guilds.admin.messages: true
            guilds.user.join: true
            guilds.user.list: true
            guilds.admin.add: true
            guilds.admin.remove: true
            guilds.admin.create: true
            guilds.user.base: true
            guilds.user.chat: true
            guilds.admin.setbase: true
            guilds.admin.save: true
            guilds.admin.load: true
            guilds.user.leave: true
            guilds.user.chat: true
            guilds.user.info: true
    guilds.admin.*:
        description: Gives access to all guilds admin commands
        children:
            guilds.admin.kick: true
            guilds.admin.toggle: true
            guilds.admin.settings: true
            guilds.admin.setting: true
            guilds.admin.add: true
            guilds.admin.remove: true
            guilds.admin.create: true
            guilds.admin.setbase: true
            guilds.admin.save: true
            guilds.admin.load: true
    guilds.user.*:
        description: Gives access to all guilds user commands
        children:
            guilds.user.join: true
            guilds.user.base: true
            guilds.user.list: true
            guilds.user.leave: true
            guilds.user.chat: true
            guilds.user.info: true
    guilds.admin.kick:
        description: Permission
        default: op
    guilds.admin.settings:
        description: Permission
        default: op
    guilds.admin.toggle:
        description: Permission
        default: op
    guilds.admin.setting:
        description: Permission
        default: op
    guilds.admin.messages:
        description: Permission
        default: op
    guilds.admin.leave:
        description: Permission
        default: true
    guilds.user.join:
        description: Permission
        default: true
    guilds.admin.add:
        description: Permission
        default: op
    guilds.admin.remove:
        description: Permission
        default: op
    guilds.admin.create:
        description: Permission
        default: op
    guilds.admin.setbase:
        description: Permission
        default: op
    guilds.user.base:
        description: Permission
        default: true
    guilds.user.chat:
        description: Permission
        default: true
    guilds.admin.save:
        description: Permission
        default: op
    guilds.admin.load:
        description: Permission
        default: op
    guilds.user.list:
        description: Permission
        default: true
    guilds.user.info:
        description: Permission
        default: true