ENABLE_CHANGE_GUILD: false
ENABLE_NO_GUILD: true
ENABLE_DEFAULT_GUILD: false
ENABLE_FRIENDLY_FIRE_PVP: false
ENABLE_BASE_ON_DEATH: false
ENABLE_CHAT_COLOR: false
ENABLE_PLAYER_GUILD_PREFIX: false
ENABLE_PLAYER_LISTNAME_COLOR: false
ENABLE_PLAYER_LISTNAME_GUILD: false
ENABLE_GUILD_CHAT_FORMAT: false
ENABLE_GUILD_JOIN_PERMISSIONS: false
ENABLE_GUILD_NAME_ON_BROADCAST: false
SET_BASE_TP_DELAY: 0
SET_CHAT_PREFIX: ''
SET_CHAT_SUFFIX: ''
SET_GUILDS_BROADCAST_COLOR: ''
SET_DEFAULT_GUILD: ''
SET_CHANGE_GUILD_TIME: 0
